[env]
TERM = "xterm-256color"

[font]
ligatures = true
size = 12.0

[window]
padding = { x = 10, y = 0 }

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"

#Colors
[colors.primary]
background = "#141414"
foreground = "#ffffd4"

[colors.cursor]
text = "#262626"
cursor = "#ccd88c"

[colors.normal]
black = "#262626"
red = "#c06d44"
green = "#afb97a"
yellow = "#c2a86c"
blue = "#44474a"
magenta = "#b4be7c"
cyan = "#778385"
white = "#ffffd4"

[colors.bright]
black = "#262626"
red = "#de7c4c"
green = "#ccd88c"
yellow = "#e2c47e"
blue = "#5a5e62"
magenta = "#d0dc8e"
cyan = "#8a989b"
white = "#ffffd4"

